Grep
gannagoodkevich/task_3 pull request #2
Opened 2019-11-11 12:58 UTC by gannagoodkevich

https://exercism.io/my/solutions/6b442a5ec43d4b32ad7905ebf50d369e

2019-11-12 12:23 UTC, KaterinaSav requested changes

2019-11-12 12:23 UTC, KaterinaSav commented on Grep/grep.rb
> +      if argument.eql?("-n")
`if argument.eql?(x)` красивее заменить на case/when 
https://github.com/rubocop-hq/ruby-style-guide#case-vs-if-else

2019-11-12 12:23 UTC, KaterinaSav commented on Grep/grep.rb
> +        line1 = line.downcase unless registr
unless registr -> if registr.present? или что-то вроде этого
стараемся делать код максимально читабельным

2019-11-12 12:23 UTC, KaterinaSav commented on Grep/grep.rb
> +          unless revert
https://github.com/rubocop-hq/ruby-style-guide#no-else-with-unless

2019-11-12 12:23 UTC, KaterinaSav commented on Grep/grep.rb
> +          end
попробуй отрефакторить код так, чтобы не стало или максимально уменьшилось количество if/elsif/else

2019-11-12 12:42 UTC, gannagoodkevich commented on Grep/grep.rb
> +          end
Хм... пока не представляю как можно это сделать. Нужна куча ифов... Надо думать долго)

2019-11-12 12:42 UTC, gannagoodkevich commented on Grep/grep.rb
> +        line1 = line.downcase unless registr
переименовала в registr_sensetive, надеюсь теперь понятнее)

2019-11-12 12:45 UTC, KaterinaSav commented on Grep/grep.rb
> +          end
Подумай)

2019-11-18 09:53 UTC, gannagoodkevich commented
Я сдедлаль...

2019-11-22 11:31 UTC, KaterinaSav requested changes

2019-11-22 11:31 UTC, KaterinaSav commented on Grep/grep.rb
> +    def grep(search_word, flags, files)
Попробуй максимально упростить греп, пока что выглядит оочень сложным, уверена есть решение проще

2019-11-22 11:33 UTC, gannagoodkevich commented on Grep/grep.rb
> +    def grep(search_word, flags, files)
Попробую)

2019-11-25 12:49 UTC, KaterinaSav approved these changes

2019-11-25 13:13 UTC, merged