Meetup
gannagoodkevich/task_3 pull request #4
Opened 2019-11-11 12:59 UTC by gannagoodkevich

https://exercism.io/my/solutions/29bbf9f265bb4ae899165a0552abdf38

2019-11-12 12:43 UTC, KaterinaSav requested changes

2019-11-12 12:43 UTC, KaterinaSav commented on Meetup/meetup.rb
> +        day_index = 1
можно создать хэш для этих данных

2019-11-12 12:43 UTC, KaterinaSav commented on Meetup/meetup.rb
> +      for i in 1..30
тебе нужно создавать очень много дат это медленно и занимает много памяти, попробуй сделать с меньшим количеством, например используя такие методы как https://apidock.com/ruby/Date/wday 
+ 1.week, и тд

2019-11-15 11:31 UTC, gannagoodkevich commented
Изменения сделаны)

2019-11-22 11:28 UTC, KaterinaSav requested changes

2019-11-22 11:28 UTC, KaterinaSav commented on Meetup/meetup.rb
> +    curr_date = Date.new(@year, @month, 1)
цифры всегда нужно выносить в константу, тк непонятно откуда они и что обозначают

2019-11-22 11:28 UTC, KaterinaSav commented on Meetup/meetup.rb
> +  def second_day(day_index)
методы одинаковые за исключением цифры, зачем тогда их столько

2019-11-22 11:28 UTC, KaterinaSav commented on Meetup/meetup.rb
> +    day_index = send("#{name_of_day}_index")
зачем тут send если по итогу все методы "#{name_of_day}_index" просто из хэша достают 
send("#{name_of_day}_index") можно заменить на @day_hash[name_of_day.to_s] и тогда не нужны повторяющиеся методы

Максимально старайся упростить код и не писать ничего лишнего, лишний код == ухудшение читабельности

2019-11-25 12:48 UTC, KaterinaSav requested changes

2019-11-25 12:48 UTC, KaterinaSav commented on Meetup/meetup.rb
> +    when :monday
Зачем тут case/when, когда можно просто @day_hash[name_of_day]

2019-11-25 12:48 UTC, KaterinaSav commented on Meetup/meetup.rb
> +      curr_date = Date.new(@year, @month, FIRST_DAY_MONTH)
код все еще повторяется

2019-11-25 14:12 UTC, KaterinaSav requested changes

2019-11-25 14:12 UTC, KaterinaSav commented on Meetup/meetup.rb
> +    @date += 1 until @date.send("#{day}?") unless schedule == :last
Параметр который приходит все класса лучше не отправлять в send, это не безопастно

2019-11-25 14:12 UTC, KaterinaSav commented on Meetup/meetup.rb
> +      @date += 2 * WEEK
Цифры непонятные

2019-11-25 14:30 UTC, KaterinaSav requested changes

2019-11-25 14:30 UTC, KaterinaSav commented on Meetup/meetup.rb
> +      @date -= 1 until @date.send("#{day}?")
все еще вызываешь  send со входящим параметром

2019-11-25 14:34 UTC, KaterinaSav approved these changes

2019-11-25 14:36 UTC, merged