solve task and make check queen-attack tests
gannagoodkevich/task_3 pull request #6
Opened 2019-11-11 13:01 UTC by gannagoodkevich

https://exercism.io/my/solutions/2b990fc043bb4fd7bde3dfdb9fbdff73

2019-11-14 14:21 UTC, KaterinaSav requested changes

2019-11-14 14:21 UTC, KaterinaSav commented on queen-attack/queen_attack.rb
> +      raise ArgumentError, 'Argument is wrong' if v[0] < 0 || v[1] < 0 || v[0] >= 8 || v[1] >= 8
Одинаковые проверки делаются на объекте, такое можно выносить в отдельный метод

2019-11-14 14:21 UTC, KaterinaSav commented on queen-attack/queen_attack.rb
> +    @board.each do |line|
Почитать map vs each

2019-11-14 14:21 UTC, KaterinaSav commented on queen-attack/queen_attack.rb
> +    end
В данном случае `@board` будет такой же как и был до 
```
@board.each do |line|
  line.each {|element| element = 0}
end
```

2019-11-14 14:21 UTC, KaterinaSav commented on queen-attack/queen_attack.rb
> +    @board = Array.new(8){Array.new(8)}
Если хочешь чтобы board был запоненый 0 `Array.new(8, 0){Array.new(8, 0)}` смотри доки объектов, в руби много синтаксического сахара, который может заменить кучу ненужного кода

2019-11-14 14:21 UTC, KaterinaSav commented on queen-attack/queen_attack.rb
> +    end
много повторяющегося кода индексы могут быть переданы как параметры, white black тоже

2019-11-18 13:08 UTC, gannagoodkevich commented
Done

2019-11-22 11:32 UTC, KaterinaSav requested changes
Упрощай и сокращай количество кода

2019-11-25 12:44 UTC, KaterinaSav approved these changes

2019-11-25 13:18 UTC, merged